config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "projects#index"

  resources :projects do
    resources :comments, only: [ :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :project
    # TODO: customise validation message tailored to business domain
    validates :body, presence: true
end

app/models/project.rb
# TODO: extract state history into own data object
class Project < ApplicationRecord
    has_many :comments, dependent: :destroy

    enum status: %i[not_started in_progress completed]

    validates :status, presence: true

    before_update :log_status_change

    # TODO: move to decorator layer
    # @return [String]
    def name
        "project-#{id}"
    end

    # TODO: move to decorator layer
    # @return [String]
    def status_tag
        I18n.t("status.#{status}")
    end

    # TODO: move to decorator layer
    # @return [String]
    def colour
        case status
        when "not_started" then "blue"
        when "in_progress" then "red"
        when "completed" then "green"
        else "grey"
        end
    end

    private

    # @return [Array, String]
    def log_status_change
        data << status
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        if comment.save
            redirect_to project, notice: "Comment posted."
        else
            redirect_to project, alert: "Error adding comment."
        end
    end

    private

    # @return [ActionController::Parameters]
    def comment_params
        params.require(:comment).permit(:body)
    end

    # @return [Project]
    def project
        Project.find(params[:project_id])
    end

    # @return [Comment]
    def comment
        project.comments.build(comment_params)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    helper_method :project, :comment

    def index
    end

    def show
    end

    def update
      if project.update(status: status)
        redirect_to project, notice: "Project updated."
      else
        render :show
      end
    end

    private

    # @return [ActionController::Parameters]
    def project_params
      params.require(:project).permit(:status)
    end

    # @return [Integer]
    def status
        project_params[:status].to_i
    end

    # @return [Project]
    def project
        Project.find(params[:id])
    end

    # @return [Comment]
    def comment
        Comment.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # @return [String]
    def site_name
        "Homey Tech Task"
    end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title=content_for(:title) || site_name
    meta name='viewport' content='width=device-width,initial-scale=1'
    meta name='apple-mobile-web-app-capable' content='yes'
    = csrf_meta_tags
    = csp_meta_tag

    = yield :head

    link rel='manifest' href='/manifest.json'
    link rel='icon' href='/icon.png' type='image/png'
    link rel='icon' href='/icon.svg' type='image/svg+xml'
    link rel='apple-touch-icon' href='/icon.png'

    / TODO: implement asset pipeline using SCSS
    = stylesheet_link_tag 'application'

  body
    header
      ul
        li= link_to 'Home', root_path
        li= link_to 'Project List', projects_path
    main
      - flash.each do |type, message|
        pre #{type}: #{message}
      = yield

app/views/projects/index.html.slim
- content_for :title do
  | #{site_name} | Project List

h1 Project List

ol
    - Project.all.each do |project|
        li
            => link_to project.name, project_path(project.id)
            | (#{project.status_tag})

app/views/projects/show.html.slim
/ TODO: maintain WCAG standards with essential markup
- content_for :title do
  | #{site_name} | #{project.name}

h1 style="color: #{project.colour}" #{project.name} (#{project.status_tag})
/ TODO: Replace inline styles with SASS and a design system
  h1 class=[project.colour] #{project.name} (#{project.status_tag})

= form_with(model: project, local: true) do |form|
  = form.select :status, options_for_select(Project.statuses, selected: Project.statuses[project.status])
  = form.submit 'Update'

h2 Comments (#{project.comments.size})

= form_with(model: [project, comment], local: true) do |form|
  = form.text_area :body
  / TODO: Replace hardcoded text using locales for consistency, mantainability and improved UX
  = form.submit 'Post'

/ TODO: extract elements to partials where appropriate for better organisation and reuse
- if project.comments.any?
  ul
    - project.comments.each do |comment|
      li
        = comment.body
        hr

h2 Status Changes (#{project.data.size})

- if project.data.any?
  ol
    - project.data.each do |state|
      li
        = I18n.t("status.#{state}")
        hr